---
- name: install latest generic kernel headers / image
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  apt:
    pkg: {{ item }}
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - linux-headers-generic
    - linux-image-generic
  register: pkgs
  until: pkgs|success

- name: remove old raring kernel headers
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  apt: name=linux-headers-3.8.0-* state=absent
  apt: name=linux-headers-generic-lts-raring state=absent
  apt: name=linux-image-3.8.0-* state=absent
  apt: name=linux-image-generic-lts-raring state=absent

- name: restart machine
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started
  sudo: false
