---
- name: install packages that are for all hosts
  apt:
    pkg: {{ item }}
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items: all
  tags:
    - deployment
    - target
  register: pkgs
  until: pkgs|success

- name: install packages that are for deployment hosts
  apt:
    pkg: {{ item }}
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items: deployment
  tags: deployment
  register: pkgs
  until: pkgs|success

- name: install packages that are for target hosts
  apt:
    pkg: {{ item }}
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items: target
  tags: target
  register: pkgs
  until: pkgs|success

- name: install common pip packages
  pip: name={{ item }} state=present
  with_items: pip

- name: unblacklist required kernel modules
  lineinfile: dest=/etc/modprobe.d/blacklist.local.conf state=absent line="{{ item }}"
  with_items:
    - blacklist e1000e
    - blacklist ixgbe

- name: load blacklisted modules
  modprobe: name={{ item }} state=present
  with_items:
    - e1000e
    - ixgbe

- name: ensure blacklisted module persistance
  lineinfile: dest=/etc/modules state=present regexp="^{{ item }}" line="{{ item }}"
  with_items:
    - e1000e
    - ixgbe
