---
- name: Perform dist-upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 600
  register: pkgs
  until: pkgs|success

- name: Install lldpd
  apt:
    pkg: lldpd
    state: latest
    update_cache: yes
    cache_valid_time: 600
  register: pkgs
  until: pkgs|success

- name: Install vlan
  apt:
    pkg: vlan
    state: latest
    update_cache: yes
    cache_valid_time: 600
  register: pkgs
  until: pkgs|success

- name: Install bridge-utils
  apt:
    pkg: bridge-utils
    state: latest
    update_cache: yes
    cache_valid_time: 600
  register: pkgs
  until: pkgs|success

- name: Install pip
  tags: rpc
  shell: "curl https://bootstrap.pypa.io/get-pip.py|python"
